-- CREATE USERS CLEVA_V9 and CLEVA_TRSV
-- -----------------------------------------------------------------

CREATE USER CLEVA_V9
  IDENTIFIED BY V9
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 10 Roles for CLEVA_V9 
  GRANT IMP_FULL_DATABASE TO CLEVA_V9 WITH ADMIN OPTION;
  GRANT DBA TO CLEVA_V9 WITH ADMIN OPTION;
  GRANT EXP_FULL_DATABASE TO CLEVA_V9 WITH ADMIN OPTION;
  GRANT RESOURCE TO CLEVA_V9 WITH ADMIN OPTION;
  GRANT IMP_FULL_DATABASE TO CLEVA_V9 WITH ADMIN OPTION;
  GRANT DATAPUMP_EXP_FULL_DATABASE TO CLEVA_V9;
  GRANT DATAPUMP_IMP_FULL_DATABASE TO CLEVA_V9;
  GRANT DBA TO CLEVA_V9 WITH ADMIN OPTION;
  GRANT EXP_FULL_DATABASE TO CLEVA_V9 WITH ADMIN OPTION;
  GRANT RESOURCE TO CLEVA_V9 WITH ADMIN OPTION;
  ALTER USER CLEVA_V9 DEFAULT ROLE ALL;
  -- 7 System Privileges for CLEVA_V9 
  GRANT UNLIMITED TABLESPACE TO CLEVA_V9 WITH ADMIN OPTION;
  GRANT UNLIMITED TABLESPACE TO CLEVA_V9 WITH ADMIN OPTION;
  GRANT ALTER SESSION TO CLEVA_V9;
  GRANT ALTER USER TO CLEVA_V9;
  GRANT CREATE USER TO CLEVA_V9;
  GRANT CREATE SESSION TO CLEVA_V9;
  GRANT DROP USER TO CLEVA_V9;
  -- 1 Tablespace Quota for CLEVA_V9 
  ALTER USER CLEVA_V9 QUOTA UNLIMITED ON USERS;


-- 

CREATE USER CLEVA_TRSV
  IDENTIFIED BY V9
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 10 Roles for CLEVA_TRSV 
  GRANT IMP_FULL_DATABASE TO CLEVA_TRSV WITH ADMIN OPTION;
  GRANT DBA TO CLEVA_TRSV WITH ADMIN OPTION;
  GRANT EXP_FULL_DATABASE TO CLEVA_TRSV WITH ADMIN OPTION;
  GRANT RESOURCE TO CLEVA_TRSV WITH ADMIN OPTION;
  GRANT IMP_FULL_DATABASE TO CLEVA_TRSV WITH ADMIN OPTION;
  GRANT DATAPUMP_EXP_FULL_DATABASE TO CLEVA_TRSV;
  GRANT DATAPUMP_IMP_FULL_DATABASE TO CLEVA_TRSV;
  GRANT DBA TO CLEVA_TRSV WITH ADMIN OPTION;
  GRANT EXP_FULL_DATABASE TO CLEVA_TRSV WITH ADMIN OPTION;
  GRANT RESOURCE TO CLEVA_TRSV WITH ADMIN OPTION;
  ALTER USER CLEVA_TRSV DEFAULT ROLE ALL;
  -- 7 System Privileges for CLEVA_TRSV 
  GRANT UNLIMITED TABLESPACE TO CLEVA_TRSV WITH ADMIN OPTION;
  GRANT UNLIMITED TABLESPACE TO CLEVA_TRSV WITH ADMIN OPTION;
  GRANT ALTER SESSION TO CLEVA_TRSV;
  GRANT ALTER USER TO CLEVA_TRSV;
  GRANT CREATE USER TO CLEVA_TRSV;
  GRANT CREATE SESSION TO CLEVA_TRSV;
  GRANT DROP USER TO CLEVA_TRSV;
  -- 1 Tablespace Quota for CLEVA_TRSV 
  ALTER USER CLEVA_TRSV QUOTA UNLIMITED ON USERS;
